//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hipparcos_DB.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hipparcos_DB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All files were downloaded and decompressed. ähnelt.
        /// </summary>
        internal static string allFilesDownloadedText {
            get {
                return ResourceManager.GetString("allFilesDownloadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successful ähnelt.
        /// </summary>
        internal static string allFilesDownloadedTitle {
            get {
                return ResourceManager.GetString("allFilesDownloadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Apply ähnelt.
        /// </summary>
        internal static string applyLabel {
            get {
                return ResourceManager.GetString("applyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The text was copied to the clipboard! ähnelt.
        /// </summary>
        internal static string copiedToClipboardText {
            get {
                return ResourceManager.GetString("copiedToClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copied to clipboard ähnelt.
        /// </summary>
        internal static string copiedToClipboardTitle {
            get {
                return ResourceManager.GetString("copiedToClipboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Edit host ähnelt.
        /// </summary>
        internal static string editHostLabel {
            get {
                return ResourceManager.GetString("editHostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string errorTitle {
            get {
                return ResourceManager.GetString("errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_application_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_application_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_arrow_000_medium_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_arrow_000_medium_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_arrow_090_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_arrow-090_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_arrow_270_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_arrow_270_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_arrow_270_medium_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_arrow_270_medium_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_arrow_270_small_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_arrow_270_small_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_arrow_curve_180_left_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_arrow_curve_180_left_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_arrow_stop_090_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_arrow-stop-090_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_arrow_stop_270_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_arrow-stop-270_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_clipboard_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_clipboard_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_control_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_control_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_control_180_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_control_180_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_control_double_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_control_double_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_control_double_180_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_control_double_180_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_control_stop_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_control_stop_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_control_stop_180_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_control_stop_180_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_cross_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_cross_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_disk_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_disk_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_disk_small_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_disk-small_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_door_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_door_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_drive_download_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_drive-download_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_exclamation__frame_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_exclamation--frame_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_exclamation_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_exclamation_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_folder_open_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_folder-open_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_funnel_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_funnel_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_gear_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_gear_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_information_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_information_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_information_button_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_information-button_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_information_white_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_information-white_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_pencil_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_pencil_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_table_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_table_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_table_paint_can_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_table-paint-can_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_table_select_row_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_table-select-row_16px_shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fugue_tick_button_16px_shadowless {
            get {
                object obj = ResourceManager.GetObject("fugue_tick-button_16px-shadowless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hipparcos1 {
            get {
                object obj = ResourceManager.GetObject("hipparcos1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name of the host are null, empty or a space. ähnelt.
        /// </summary>
        internal static string invalidHostnameText {
            get {
                return ResourceManager.GetString("invalidHostnameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t disturb me! I&apos;m loading. ;-) ähnelt.
        /// </summary>
        internal static string jokeLoadingText {
            get {
                return ResourceManager.GetString("jokeLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading ähnelt.
        /// </summary>
        internal static string jokeLoadingTitle {
            get {
                return ResourceManager.GetString("jokeLoadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading file... ähnelt.
        /// </summary>
        internal static string loadingFile {
            get {
                return ResourceManager.GetString("loadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging file saved. ähnelt.
        /// </summary>
        internal static string loggingFileSavedText {
            get {
                return ResourceManager.GetString("loggingFileSavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successful ähnelt.
        /// </summary>
        internal static string loggingFileSavedTitle {
            get {
                return ResourceManager.GetString("loggingFileSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some files are missing. Please download all files in the main window. ähnelt.
        /// </summary>
        internal static string missingDownloadFilesText1 {
            get {
                return ResourceManager.GetString("missingDownloadFilesText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some files are missing. Please use the download button to download all files. ähnelt.
        /// </summary>
        internal static string missingDownloadFilesText2 {
            get {
                return ResourceManager.GetString("missingDownloadFilesText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing files ähnelt.
        /// </summary>
        internal static string missingDownloadFilesTitle {
            get {
                return ResourceManager.GetString("missingDownloadFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number is out of range. The number to be entered must be greater than zero and less than the maximum value. ähnelt.
        /// </summary>
        internal static string numberOutOfRangeText {
            get {
                return ResourceManager.GetString("numberOutOfRangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number out of range ähnelt.
        /// </summary>
        internal static string numberOutOfRangeTitle {
            get {
                return ResourceManager.GetString("numberOutOfRangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some files couldn&apos;t downloaded and decompressed. Read the logged error messages! ähnelt.
        /// </summary>
        internal static string someFilesNotDowloadedText {
            get {
                return ResourceManager.GetString("someFilesNotDowloadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... ähnelt.
        /// </summary>
        internal static string someFilesNotDowloadedTitle {
            get {
                return ResourceManager.GetString("someFilesNotDowloadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The input is not a natural number. Make sure the input is a natural number, for example: 1, 2, 3, ... ähnelt.
        /// </summary>
        internal static string wrongNumberFormatText {
            get {
                return ResourceManager.GetString("wrongNumberFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong number format ähnelt.
        /// </summary>
        internal static string wrongNumberFormatTitle {
            get {
                return ResourceManager.GetString("wrongNumberFormatTitle", resourceCulture);
            }
        }
    }
}
